# version: '3.8'

services:
  db:
    ports:
      - "3307:3306" # เปิด Port ให้เครื่องมืออย่าง DBeaver/DataGrip เข้าถึงได้ตอน Dev

  backend:
    volumes:
      - ./backend:/app # Map โค้ดในเครื่องเข้าไปใน Container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=run.py
    # สั่ง Override CMD ทับ Gunicorn ด้วย Flask Dev Server
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]

  client:
    build:
      context: ./client
      target: builder
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "443:443"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  villager: # Villager Side (รัน 8080)
        build:
          context: ./vilager-side
          target: builder
        volumes:
          - ./vilager-side:/app
          - /app/node_modules
        ports:
          - "8080:8080" # แมปพอร์ตเครื่องเรา 8080 เข้า Container 8080
        environment:
          - CHOKIDAR_USEPOLLING=true
        # สั่งให้รัน dev server บนพอร์ต 8080
        command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]

  ai_service:
    volumes:
      - ./ai_service:/app # Map โค้ดในเครื่องเข้าไปใน Container
      - /app/node_modules # ป้องกัน node_modules ในเครื่องไปทับใน Container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
