# version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    restart: always
    env_file: .env
    volumes:
      - uploads_data:/app/app/static/uploads
    depends_on:
      - db
    networks:
      - app-network

  ai_service:
    build:
      context: ./ai_service
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./ai_service:/ai_service           # ดึงโค้ดจากเครื่องเราไปเชื่อมกับใน Container (แก้โค้ดปุ๊บ Server รีสตาร์ทปั๊บ)
      - /ai_service/node_modules           # ป้องกันไม่ให้ node_modules จากเครื่องเราไปกวนใน Container
    networks:
      - app-network

  client:
    build:
      context: ./client
    restart: always
    depends_on:
      - backend
      - ai_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  uploads_data:
