[pytest]
markers =
    hrm: human resource management tests
    report: report/task assignment tests
    bdd: behavior-driven tests
    task: task management API tests
    heatmap: heatmap api tests
    monthly_report: monthly report tests
